import ts from "typescript";
import { hoistVariables } from "./hoist.js";
import { explodeBody, generateStepFunction } from "./emit.js";
import { findYieldInNestedFunction, findTryCatchAcrossYield } from "./detect.js";
import { rewriteVariableRefs } from "./rewrite-refs.js";

export interface TransformResult {
  code: string;
  errors: string[];
}

export function transform(source: string, filename: string = "script.ts"): TransformResult {
  const sourceFile = ts.createSourceFile(filename, source, ts.ScriptTarget.Latest, true);
  const errors: string[] = [];

  // Find the main export function
  const mainFn = findMainFunction(sourceFile);
  if (!mainFn) {
    return { code: "", errors: ["No exported async function 'main' found"] };
  }

  if (!mainFn.body) {
    return { code: "", errors: ["main function has no body"] };
  }

  // Check for unsupported patterns
  const nestedYield = findYieldInNestedFunction(mainFn.body, false);
  if (nestedYield) {
    errors.push(nestedYield);
  }
  const tryCatchYield = findTryCatchAcrossYield(mainFn.body);
  if (tryCatchYield) {
    errors.push(tryCatchYield);
  }
  if (errors.length > 0) {
    return { code: "", errors };
  }

  // Step 1: Hoist variables
  const bodyStmts = [...mainFn.body.statements];
  const { hoisted, statements } = hoistVariables(bodyStmts, ts.factory);

  // Step 1.5: Rewrite references to hoisted vars (x → state.x)
  const hoistedNames = new Set(hoisted.map((h) => h.name));
  const rewritten = rewriteVariableRefs(statements, hoistedNames);

  // Step 2: Explode into state machine cases
  // We need a source file that contains the hoisted statements for line numbers
  // Since the hoisted statements reference the original positions, use the original sourceFile
  const exploded = explodeBody(rewritten, sourceFile);

  // Step 3: Generate step function
  const stepCode = generateStepFunction(
    exploded,
    hoisted.map((h) => h.name),
  );

  // Wrap with header
  const header = `// Auto-generated by @ocmdx/transform — do not edit\n`;
  const code = header + stepCode + "\n";

  return { code, errors: [] };
}

function findMainFunction(sourceFile: ts.SourceFile): ts.FunctionDeclaration | undefined {
  for (const stmt of sourceFile.statements) {
    if (
      ts.isFunctionDeclaration(stmt) &&
      stmt.name?.text === "main" &&
      stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword) &&
      stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.AsyncKeyword)
    ) {
      return stmt;
    }
  }
  return undefined;
}
